// Grammar → illustration map. Files live in `public/grammar-images/` as
// original flat-style SVGs generated by `scripts/gen-grammar-images.mjs`
// (no third-party or textbook art) — mirrors `src/lib/lessonImages.ts`. A
// grammar point without a file simply shows no illustration.
//
// Keys must match a grammar item's `id` exactly. Values are filenames served
// from `/grammar-images/<file>`.

export type GrammarImage = {
  file: string;
  captionEn: string;
  captionVi: string;
};

const GRAMMAR_IMAGES: Record<string, GrammarImage> = {
  // Lesson 1
  l1_desu: {
    file: "l1_wa_desu.svg",
    captionEn: "Introducing yourself — 'I am ~'.",
    captionVi: "Tự giới thiệu — 'Tôi là ~'.",
  },
  l1_ka: {
    file: "l1_ka.svg",
    captionEn: "Turning a sentence into a question with か.",
    captionVi: "Biến một câu thành câu hỏi bằng か.",
  },
  l1_mo: {
    file: "l1_mo.svg",
    captionEn: "Saying 'me too' — the comment applies to both.",
    captionVi: "Nói 'tôi cũng vậy' — điều đó đúng với cả hai.",
  },
  l1_no: {
    file: "l1_no.svg",
    captionEn: "X's Y — showing who something belongs to.",
    captionVi: "X của Y — cho biết vật thuộc về ai.",
  },

  // Lesson 2
  l2_kore_sore_are: {
    file: "l2_kore_sore_are.svg",
    captionEn: "Pointing to say 'this / that / that over there'.",
    captionVi: "Chỉ vào vật để nói 'cái này / cái đó / cái kia'.",
  },
  l2_kono_sono_ano: {
    file: "l2_kono_sono_ano.svg",
    captionEn: "Pointing out a specific 'this ~' or 'that ~' noun.",
    captionVi: "Chỉ rõ một danh từ cụ thể 'cái ~ này/đó/kia'.",
  },
  l2_sou_desu: {
    file: "l2_sou_desu.svg",
    captionEn: "○ for correct, × for wrong.",
    captionVi: "○ là đúng, × là sai.",
  },
  l2_ka_ka: {
    file: "l2_ka_ka.svg",
    captionEn: "Choosing between two options.",
    captionVi: "Chọn giữa hai lựa chọn.",
  },

  // Lesson 3
  l3_koko_soko_asoko: {
    file: "l3_koko_soko_asoko.svg",
    captionEn: "'Here / there / over there' on a map.",
    captionVi: "'Ở đây / ở đó / ở đằng kia' trên bản đồ.",
  },
  l3_wa_place: {
    file: "l3_wa_place.svg",
    captionEn: "Saying where something or someone is.",
    captionVi: "Nói vật gì đó hoặc ai đó đang ở đâu.",
  },

  // Lesson 4
  l4_time: {
    file: "l4_time.svg",
    captionEn: "Telling the time.",
    captionVi: "Nói giờ.",
  },
  l4_kara_made: {
    file: "l4_kara_made.svg",
    captionEn: "From a start point to an end point.",
    captionVi: "Từ điểm bắt đầu đến điểm kết thúc.",
  },
  l4_verb_polite: {
    file: "l4_verb_polite.svg",
    captionEn: "The four polite verb endings across time.",
    captionVi: "Bốn dạng đuôi động từ lịch sự theo thời gian.",
  },

  // Lesson 5
  l5_e_ikimasu: {
    file: "l5_e_ikimasu.svg",
    captionEn: "Heading toward a destination.",
    captionVi: "Hướng đến một điểm đến.",
  },
  l5_de_vehicle: {
    file: "l5_de_vehicle.svg",
    captionEn: "The vehicle used to get there.",
    captionVi: "Phương tiện dùng để đến đó.",
  },
  l5_to_person: {
    file: "l5_to_person.svg",
    captionEn: "The person you go somewhere with.",
    captionVi: "Người mà bạn cùng đi đâu đó.",
  },

  // Lesson 6
  l6_wo_object: {
    file: "l6_wo_object.svg",
    captionEn: "The thing an action is done to.",
    captionVi: "Vật mà hành động tác động vào.",
  },
  l6_de_place: {
    file: "l6_de_place.svg",
    captionEn: "Where an action takes place.",
    captionVi: "Nơi hành động diễn ra.",
  },
  l6_masenka_mashou: {
    file: "l6_masenka_mashou.svg",
    captionEn: "Inviting someone to do something together.",
    captionVi: "Rủ ai đó cùng làm việc gì.",
  },

  // Lesson 7
  l7_de_tool: {
    file: "l7_de_tool.svg",
    captionEn: "The tool or method used to do something.",
    captionVi: "Công cụ hoặc cách thức dùng để làm việc gì.",
  },
  l7_agemasu_moraimasu: {
    file: "l7_agemasu_moraimasu.svg",
    captionEn: "Giving and receiving.",
    captionVi: "Cho và nhận.",
  },
  l7_mou_mashita: {
    file: "l7_mou_mashita.svg",
    captionEn: "Already finished doing something.",
    captionVi: "Đã làm xong việc gì đó rồi.",
  },

  // Lesson 8
  l8_i_adj: {
    file: "l8_i_adj.svg",
    captionEn: "Describing qualities with い-adjectives.",
    captionVi: "Miêu tả tính chất bằng tính từ đuôi い.",
  },
  l8_na_adj: {
    file: "l8_na_adj.svg",
    captionEn: "Describing qualities with な-adjectives.",
    captionVi: "Miêu tả tính chất bằng tính từ đuôi な.",
  },
  l8_ga_but: {
    file: "l8_ga_but.svg",
    captionEn: "Connecting two contrasting ideas.",
    captionVi: "Nối hai ý trái ngược nhau.",
  },

  // Lesson 9
  l9_ga_suki: {
    file: "l9_ga_suki.svg",
    captionEn: "Saying what you like or are good at.",
    captionVi: "Nói điều bạn thích hoặc giỏi.",
  },
  l9_ga_wakarimasu: {
    file: "l9_ga_wakarimasu.svg",
    captionEn: "Understanding something, or having something.",
    captionVi: "Hiểu điều gì đó, hoặc có điều gì đó.",
  },
  l9_kara_reason: {
    file: "l9_kara_reason.svg",
    captionEn: "Giving a reason for something.",
    captionVi: "Đưa ra lý do cho điều gì đó.",
  },

  // Lesson 10
  l10_arimasu_imasu: {
    file: "l10_arimasu_imasu.svg",
    captionEn: "There is/are — things vs. people and animals.",
    captionVi: "Có ~ — đồ vật khác với người và động vật.",
  },
  l10_position: {
    file: "l10_position.svg",
    captionEn: "Describing position — above, below, inside.",
    captionVi: "Miêu tả vị trí — trên, dưới, trong.",
  },

  // Lesson 11
  l11_counters: {
    file: "l11_counters.svg",
    captionEn: "Counting objects and people.",
    captionVi: "Đếm đồ vật và người.",
  },
  l11_frequency: {
    file: "l11_frequency.svg",
    captionEn: "How often something happens.",
    captionVi: "Tần suất điều gì đó xảy ra.",
  },

  // Lesson 12
  l12_past_noun_adj: {
    file: "l12_past_noun_adj.svg",
    captionEn: "Past tense of nouns and な-adjectives.",
    captionVi: "Thì quá khứ của danh từ và tính từ đuôi な.",
  },
  l12_past_i_adj: {
    file: "l12_past_i_adj.svg",
    captionEn: "Past tense of い-adjectives.",
    captionVi: "Thì quá khứ của tính từ đuôi い.",
  },
  l12_comparison: {
    file: "l12_comparison.svg",
    captionEn: "Comparing two or more things.",
    captionVi: "So sánh hai hoặc nhiều thứ.",
  },

  // Lesson 13
  l13_hoshii: {
    file: "l13_hoshii.svg",
    captionEn: "Wanting a thing.",
    captionVi: "Muốn một vật gì đó.",
  },
  l13_tai: {
    file: "l13_tai.svg",
    captionEn: "Wanting to do an action.",
    captionVi: "Muốn làm một việc gì đó.",
  },
  l13_ni_purpose: {
    file: "l13_ni_purpose.svg",
    captionEn: "The purpose of going somewhere.",
    captionVi: "Mục đích của việc đi đến đâu đó.",
  },

  // Lesson 14
  l14_te_form: {
    file: "l14_te_form.svg",
    captionEn: "The connecting verb form.",
    captionVi: "Dạng động từ dùng để nối câu.",
  },
  l14_te_kudasai: {
    file: "l14_te_kudasai.svg",
    captionEn: "Making a polite request.",
    captionVi: "Đưa ra một lời nhờ lịch sự.",
  },
  l14_te_imasu: {
    file: "l14_te_imasu.svg",
    captionEn: "An action happening right now.",
    captionVi: "Hành động đang diễn ra ngay bây giờ.",
  },

  // Lesson 15
  l15_te_mo_ii: {
    file: "l15_te_mo_ii.svg",
    captionEn: "Asking or giving permission.",
    captionVi: "Xin hoặc cho phép.",
  },
  l15_te_wa_ikemasen: {
    file: "l15_te_wa_ikemasen.svg",
    captionEn: "Forbidding an action.",
    captionVi: "Cấm một hành động.",
  },
  l15_te_imasu_state: {
    file: "l15_te_imasu_state.svg",
    captionEn: "An ongoing state or daily habit.",
    captionVi: "Một trạng thái kéo dài hoặc thói quen hằng ngày.",
  },

  // Lesson 16
  l16_te_connect: {
    file: "l16_te_connect.svg",
    captionEn: "Doing actions one after another.",
    captionVi: "Làm các việc lần lượt nối tiếp nhau.",
  },
  l16_te_kara: {
    file: "l16_te_kara.svg",
    captionEn: "Doing something after finishing another.",
    captionVi: "Làm việc gì đó sau khi xong việc khác.",
  },
  l16_adj_te: {
    file: "l16_adj_te.svg",
    captionEn: "Joining two descriptions together.",
    captionVi: "Nối hai tính chất lại với nhau.",
  },

  // Lesson 17
  l17_nai_form: {
    file: "l17_nai_form.svg",
    captionEn: "The plain negative verb form.",
    captionVi: "Dạng phủ định thông thường của động từ.",
  },
  l17_naide_kudasai: {
    file: "l17_naide_kudasai.svg",
    captionEn: "Asking someone not to do something.",
    captionVi: "Nhờ ai đó đừng làm việc gì.",
  },
  l17_nakereba: {
    file: "l17_nakereba.svg",
    captionEn: "Obligation, and its opposite.",
    captionVi: "Sự bắt buộc, và điều ngược lại.",
  },

  // Lesson 18
  l18_dict_form: {
    file: "l18_dict_form.svg",
    captionEn: "The plain dictionary form of a verb.",
    captionVi: "Dạng từ điển thông thường của động từ.",
  },
  l18_koto_ga_dekimasu: {
    file: "l18_koto_ga_dekimasu.svg",
    captionEn: "Expressing ability — 'can do ~'.",
    captionVi: "Diễn tả khả năng — 'có thể làm ~'.",
  },
  l18_mae_ni: {
    file: "l18_mae_ni.svg",
    captionEn: "Doing something before another action.",
    captionVi: "Làm việc gì đó trước một hành động khác.",
  },

  // Lesson 19
  l19_ta_form: {
    file: "l19_ta_form.svg",
    captionEn: "The plain past verb form.",
    captionVi: "Dạng quá khứ thông thường của động từ.",
  },
  l19_ta_koto_ga_arimasu: {
    file: "l19_ta_koto_ga_arimasu.svg",
    captionEn: "Talking about a past experience.",
    captionVi: "Nói về một trải nghiệm trong quá khứ.",
  },
  l19_tari_tari: {
    file: "l19_tari_tari.svg",
    captionEn: "Listing a few example actions.",
    captionVi: "Liệt kê một vài hành động tiêu biểu.",
  },
  l19_narimasu: {
    file: "l19_narimasu.svg",
    captionEn: "Expressing change — 'become ~'.",
    captionVi: "Diễn tả sự thay đổi — 'trở nên ~'.",
  },

  // Lesson 20
  l20_plain_form: {
    file: "l20_plain_form.svg",
    captionEn: "Casual speech among friends and family.",
    captionVi: "Lời nói thân mật giữa bạn bè và gia đình.",
  },

  // Lesson 21
  l21_to_omoimasu: {
    file: "l21_to_omoimasu.svg",
    captionEn: "Stating an opinion or guess.",
    captionVi: "Nêu một ý kiến hoặc phỏng đoán.",
  },
  l21_to_iimashita: {
    file: "l21_to_iimashita.svg",
    captionEn: "Reporting what someone said.",
    captionVi: "Thuật lại điều ai đó đã nói.",
  },
  l21_deshou: {
    file: "l21_deshou.svg",
    captionEn: "Seeking agreement — 'right?'.",
    captionVi: "Tìm kiếm sự đồng tình — 'phải không?'.",
  },

  // Lesson 22
  l22_noun_modify: {
    file: "l22_noun_modify.svg",
    captionEn: "Describing a noun with a whole clause.",
    captionVi: "Miêu tả một danh từ bằng cả một mệnh đề.",
  },
  l22_donna: {
    file: "l22_donna.svg",
    captionEn: "Asking 'what kind of ~?'.",
    captionVi: "Hỏi 'loại ~ như thế nào?'.",
  },

  // Lesson 23
  l23_toki: {
    file: "l23_toki.svg",
    captionEn: "Describing when something happens.",
    captionVi: "Miêu tả thời điểm điều gì đó xảy ra.",
  },
  l23_to_conditional: {
    file: "l23_to_conditional.svg",
    captionEn: "An automatic result — 'whenever ~, then ~'.",
    captionVi: "Một kết quả tự nhiên — 'hễ ~ thì ~'.",
  },
  l23_wo_movement: {
    file: "l23_wo_movement.svg",
    captionEn: "Moving through, off, or turning at a place.",
    captionVi: "Di chuyển qua, rời khỏi, hoặc rẽ tại một nơi.",
  },

  // Lesson 24
  l24_kuremasu: {
    file: "l24_kuremasu.svg",
    captionEn: "Someone gives something to me.",
    captionVi: "Ai đó cho tôi một thứ gì đó.",
  },
  l24_te_giving: {
    file: "l24_te_giving.svg",
    captionEn: "Giving and receiving favours.",
    captionVi: "Giúp đỡ và nhận được sự giúp đỡ.",
  },

  // Lesson 25
  l25_tara: {
    file: "l25_tara.svg",
    captionEn: "A conditional — 'if / once ~ happens'.",
    captionVi: "Điều kiện — 'nếu / một khi ~ xảy ra'.",
  },
  l25_temo: {
    file: "l25_temo.svg",
    captionEn: "'Even if ~' — the result doesn't change.",
    captionVi: "'Dù ~' — kết quả vẫn không đổi.",
  },
};

export function getGrammarImage(id: string): GrammarImage | null {
  return GRAMMAR_IMAGES[id] ?? null;
}
