// Lesson illustrations. Files live in `public/lesson-images/` as original flat-style
// SVGs generated by `scripts/gen-lesson-images.mjs` (no third-party or textbook art).
// A lesson without a file simply shows no illustration.
// NOTE: no artwork or text from the Minna no Nihongo scan is used here; captions are
// original and the book informs only which topic each lesson covers.
// See public/lesson-images/README.md.

export type LessonImage = {
  file: string;
  captionEn: string;
  captionVi: string;
};

// One hero illustration per lesson. Keys are lesson numbers (1–25).
export const LESSON_HEROES: Record<number, LessonImage> = {
  1: {
    file: "hero-l01.svg",
    captionEn:
      "Two people meeting for the first time and introducing themselves.",
    captionVi: "Hai người gặp nhau lần đầu và tự giới thiệu.",
  },
  2: {
    file: "hero-l02.svg",
    captionEn: "A person holding up an object and asking what it is.",
    captionVi: "Một người cầm một vật lên và hỏi đó là cái gì.",
  },
  3: {
    file: "hero-l03.svg",
    captionEn: "A shopper asking a clerk where something is inside a store.",
    captionVi: "Một khách hàng hỏi nhân viên xem đồ vật ở đâu trong cửa hàng.",
  },
  4: {
    file: "hero-l04.svg",
    captionEn: "A clock beside someone starting their daily routine.",
    captionVi:
      "Một chiếc đồng hồ bên cạnh người đang bắt đầu sinh hoạt hằng ngày.",
  },
  5: {
    file: "hero-l05.svg",
    captionEn: "A traveller heading to a destination by train.",
    captionVi: "Một người đi đến điểm đến bằng tàu điện.",
  },
  6: {
    file: "hero-l06.svg",
    captionEn: "Friends eating and drinking together at a table.",
    captionVi: "Bạn bè cùng nhau ăn uống ở bàn.",
  },
  7: {
    file: "hero-l07.svg",
    captionEn: "One person handing a wrapped gift to another.",
    captionVi: "Một người trao món quà đã gói cho người khác.",
  },
  8: {
    file: "hero-l08.svg",
    captionEn: "Cherry blossoms and a tall mountain, one pretty and one high.",
    captionVi: "Hoa anh đào và ngọn núi cao — một đẹp, một cao.",
  },
  9: {
    file: "hero-l09.svg",
    captionEn: "Someone smiling at a hobby they love.",
    captionVi: "Một người mỉm cười với sở thích mình yêu thích.",
  },
  10: {
    file: "hero-l10.svg",
    captionEn: "A room with a cat under the table and books on a shelf.",
    captionVi: "Một căn phòng có con mèo dưới bàn và sách trên kệ.",
  },
  11: {
    file: "hero-l11.svg",
    captionEn: "Counting apples one by one on a table.",
    captionVi: "Đếm từng quả táo trên bàn.",
  },
  12: {
    file: "hero-l12.svg",
    captionEn:
      "Two items on a scale being compared, one larger than the other.",
    captionVi:
      "Hai món đồ trên cân đang được so sánh, một cái lớn hơn cái kia.",
  },
  13: {
    file: "hero-l13.svg",
    captionEn: "A person daydreaming about something they want.",
    captionVi: "Một người mơ mộng về điều mình muốn.",
  },
  14: {
    file: "hero-l14.svg",
    captionEn: "Someone politely asking another person to do something.",
    captionVi: "Một người lịch sự nhờ người khác làm việc gì đó.",
  },
  15: {
    file: "hero-l15.svg",
    captionEn: "An 'OK' sign and a 'no entry' sign side by side.",
    captionVi: "Một biển 'được phép' và một biển 'cấm' đặt cạnh nhau.",
  },
  16: {
    file: "hero-l16.svg",
    captionEn: "A short checklist of steps done one after another.",
    captionVi: "Một danh sách các bước làm lần lượt theo thứ tự.",
  },
  17: {
    file: "hero-l17.svg",
    captionEn: "A person raising a hand to say 'please don't'.",
    captionVi: "Một người giơ tay ra hiệu 'xin đừng'.",
  },
  18: {
    file: "hero-l18.svg",
    captionEn: "Someone confidently showing they can do a task.",
    captionVi: "Một người tự tin cho thấy mình có thể làm được việc.",
  },
  19: {
    file: "hero-l19.svg",
    captionEn: "A traveller recalling places they have visited before.",
    captionVi: "Một người du lịch nhớ lại những nơi đã từng đến.",
  },
  20: {
    file: "hero-l20.svg",
    captionEn: "Two friends chatting casually and relaxed.",
    captionVi: "Hai người bạn trò chuyện thân mật, thoải mái.",
  },
  21: {
    file: "hero-l21.svg",
    captionEn: "A person with a thought bubble sharing an opinion.",
    captionVi: "Một người với bong bóng suy nghĩ đang nêu ý kiến.",
  },
  22: {
    file: "hero-l22.svg",
    captionEn: "Pointing out one specific person in a crowd.",
    captionVi: "Chỉ ra một người cụ thể giữa đám đông.",
  },
  23: {
    file: "hero-l23.svg",
    captionEn: "A person turning a corner along a street.",
    captionVi: "Một người rẽ ở góc phố dọc con đường.",
  },
  24: {
    file: "hero-l24.svg",
    captionEn: "A friend kindly doing someone a favour.",
    captionVi: "Một người bạn tốt bụng giúp đỡ ai đó.",
  },
  25: {
    file: "hero-l25.svg",
    captionEn: "A signpost showing two possible 'if' paths ahead.",
    captionVi: "Một biển chỉ đường cho thấy hai lối 'nếu' phía trước.",
  },
};

export function lessonImageSrc(file: string): string {
  return `/lesson-images/${file}`;
}

export function getLessonHero(lesson: number): LessonImage | null {
  return LESSON_HEROES[lesson] ?? null;
}
