// Curated word → illustration map. Files live in `public/word-images/` and are
// meant to be hand-picked いらすとや (irasutoya.com) illustrations for personal,
// non-commercial study use. A word not listed here simply shows no illustration.
// See public/word-images/README.md for how to add more.
//
// Keys must match a vocab item's `word` exactly. Values are filenames served
// from `/word-images/<file>`.
const WORD_IMAGES: Record<string, string> = {
  猫: "cat.png",
  犬: "dog.png",
  魚: "fish.png",
  鳥: "bird.png",
  車: "car.png",
  自転車: "bicycle.png",
  バス: "bus.png",
  電車: "train.png",
  飛行機: "airplane.png",
  水: "water.png",
  本: "book.png",
  傘: "umbrella.png",
  かぎ: "key.png",
  鉛筆: "pencil.png",
  新聞: "newspaper.png",
  机: "desk.png",
  いす: "chair.png",
  ノート: "notebook.png",
  カメラ: "camera.png",
  コーヒー: "coffee.png",
  紅茶: "tea.png",
  病院: "hospital.png",
  銀行: "bank.png",
  駅: "station.png",
  学校: "school.png",
  大学: "university.png",
  会社: "company.png",
  卵: "egg.png",
  手紙: "letter.png",
  パン: "bread.png",
  レストラン: "restaurant.png",
  お金: "money.png",
  切符: "ticket.png",
  シャツ: "shirt.png",
  靴: "shoes.png",
  帽子: "hat.png",
  山: "mountain.png",
  川: "river.png",
  海: "sea.png",
  空: "sky.png",
  雪: "snow.png",
  花: "flower.png",
  木: "tree.png",
  音楽: "music.png",
  映画: "movie.png",
  写真: "photo.png",
  公園: "park.png",
  ドア: "door.png",
  窓: "window.png",
  りんご: "apple.png",
  ケーキ: "cake.png",
  牛肉: "beef.png",
  とり肉: "chicken.png",
  電話: "telephone.png",
  時計: "clock.png",
  顔: "face.png",
  口: "mouth.png",
  耳: "ear.png",
  目: "eye.png",
  手: "hand.png",
  足: "foot.png",
  月: "moon.png",
  橋: "bridge.png",
};

export function getWordImage(word: string): string | null {
  const file = WORD_IMAGES[word];
  return file ? `/word-images/${file}` : null;
}
