// Applies authored lesson-expansion content (scripts/content/expansions.cjs) to
// the data files, making each lesson 2–3× longer:
//   • appends example sentences to grammar points (n5-grammar.json)
//   • appends explanation paragraphs + pitfalls (n5-grammar-details.json)
//   • appends authored practice exercises (n5-lesson-blocks.json)
//
// New example sentences are authored as { jp, en, vi } only. This script inserts
// them, then runs the canonical tokenizer (scripts/tokenize-jp.cjs) so tokens /
// romaji / romajiChunks are generated by the SAME code path as existing
// examples, then derives the kana `reading` from those tokens. Any sentence
// containing a kanji word the tokenizer can't read is reported for manual review
// — that is the accuracy safety net.
//
// Run: node scripts/expand-content.cjs
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const DATA = path.join(__dirname, "..", "data");
const content = require("./content/expansions.cjs");

const readJSON = (f) => JSON.parse(fs.readFileSync(path.join(DATA, f), "utf8"));
const writeJSON = (f, v) =>
  fs.writeFileSync(path.join(DATA, f), JSON.stringify(v, null, 2) + "\n");

const warnings = [];
let addedExamples = 0;
let addedExpl = 0;
let addedPitfalls = 0;
let addedExercises = 0;

// ── 1. Merge example sentences (jp/en/vi) into grammar points ────────────────
const grammar = readJSON("n5-grammar.json");
const grammarById = new Map(grammar.map((g) => [g.id, g]));

for (const [id, examples] of Object.entries(content.examples || {})) {
  const g = grammarById.get(id);
  if (!g) {
    warnings.push(`examples: unknown grammar id "${id}" — skipped`);
    continue;
  }
  const seen = new Set(g.examples.map((e) => e.jp));
  for (const ex of examples) {
    if (seen.has(ex.jp)) continue;
    // Insert with jp/en/vi now; tokenizer fills tokens/romaji/romajiChunks and
    // we derive `reading` afterwards.
    g.examples.push({ jp: ex.jp, reading: "", en: ex.en, vi: ex.vi });
    seen.add(ex.jp);
    addedExamples++;
  }
}
writeJSON("n5-grammar.json", grammar);

// ── 2. Run the canonical tokenizer over everything ───────────────────────────
console.log("Running tokenizer (kuromoji)…");
execSync("node scripts/tokenize-jp.cjs", {
  cwd: path.join(__dirname, ".."),
  stdio: "inherit",
});

// ── 3. Derive `reading` from tokens for any example missing it; validate ─────
const flat = (tokens) => (tokens || []).flat();
const readingFromTokens = (tokens) =>
  flat(tokens)
    .map((s) => s.f ?? s.t)
    .join("");
const KANJI_RE = /[㐀-鿿々]/;

// kuromoji/IPADIC defaults some words to formal readings that N5 textbooks
// don't use. Normalise them to the reading learners are taught. Substring
// replacement also fixes derived compounds (にっぽんじん → にほんじん).
// kuromoji does not apply the euphonic gemination (促音) that 一 triggers before
// certain counters, reading 一週間 as いちしゅうかん instead of the correct
// いっしゅうかん. These fixes restore the readings N5 learners are taught. The
// reading-validator only catches *missing* furigana, so wrong-but-present
// readings like these must be corrected explicitly.
const READING_FIXES = [
  [/にっぽん/g, "にほん"],
  [/いちしゅうかん/g, "いっしゅうかん"],
  [/いちかげつ/g, "いっかげつ"],
  [/いちかい/g, "いっかい"],
];
const ROMAJI_FIXES = [
  [/nippon/g, "nihon"],
  [/ichishuukan/g, "isshuukan"],
  [/ichikagetsu/g, "ikkagetsu"],
  [/ichikai/g, "ikkai"],
];
function normalizeReadings(item) {
  for (const seg of flat(item.tokens)) {
    if (seg.f)
      for (const [re, to] of READING_FIXES) seg.f = seg.f.replace(re, to);
  }
  if (item.reading)
    for (const [re, to] of READING_FIXES)
      item.reading = item.reading.replace(re, to);
  if (item.romaji)
    for (const [re, to] of ROMAJI_FIXES)
      item.romaji = item.romaji.replace(re, to);
  if (Array.isArray(item.romajiChunks))
    item.romajiChunks = item.romajiChunks.map((c) => {
      for (const [re, to] of ROMAJI_FIXES) c = c.replace(re, to);
      return c;
    });
}

const grammar2 = readJSON("n5-grammar.json");
for (const g of grammar2) {
  for (const ex of g.examples) {
    if (!ex.reading) ex.reading = readingFromTokens(ex.tokens);
    normalizeReadings(ex);
    // Safety net: a kanji-bearing segment with no furigana means the tokenizer
    // did not recognise the word — likely a typo or non-standard Japanese.
    for (const seg of flat(ex.tokens)) {
      if (KANJI_RE.test(seg.t) && !seg.f) {
        warnings.push(
          `reading: "${g.id}" example «${ex.jp}» — no furigana for "${seg.t}" (review Japanese)`,
        );
      }
    }
  }
}
writeJSON("n5-grammar.json", grammar2);

// ── 3b. Ensure every example has an alignment entry of the right length ───────
// Existing authored alignments are left untouched; newly added examples get a
// length-correct all-null entry (word-highlighting stays off for them, all
// other content renders normally). This satisfies the enrichment test.
const alignments = readJSON("n5-alignments.json");
let addedAlign = 0;
for (const g of grammar2) {
  g.examples.forEach((ex, i) => {
    const key = `g:${g.id}:${i}`;
    const n = (ex.tokens || []).length;
    if (!alignments[key]) {
      alignments[key] = {
        en: Array(n).fill(null),
        vi: Array(n).fill(null),
      };
      addedAlign++;
    }
  });
}
writeJSON("n5-alignments.json", alignments);

// Keep dialogue readings consistent with the same normalisation.
const dialogues = readJSON("n5-dialogues.json");
for (const d of dialogues) for (const line of d.lines) normalizeReadings(line);
writeJSON("n5-dialogues.json", dialogues);

// ── 4. Merge explanation paragraphs + pitfalls ───────────────────────────────
const details = readJSON("n5-grammar-details.json");
for (const [id, add] of Object.entries(content.explanations || {})) {
  if (!details[id]) {
    warnings.push(`explanations: unknown grammar id "${id}" — skipped`);
    continue;
  }
  for (const lang of ["en", "vi"]) {
    const d = details[id][lang];
    const a = add[lang];
    if (!d || !a) continue;
    if (a.explanation) {
      const seen = new Set(d.explanation);
      for (const p of a.explanation)
        if (!seen.has(p)) {
          d.explanation.push(p);
          if (lang === "en") addedExpl++;
        }
    }
    if (a.pitfalls) {
      const seen = new Set(d.pitfalls);
      for (const p of a.pitfalls)
        if (!seen.has(p)) {
          d.pitfalls.push(p);
          if (lang === "en") addedPitfalls++;
        }
    }
  }
}
writeJSON("n5-grammar-details.json", details);

// ── 5. Insert authored exercise blocks per lesson ────────────────────────────
const layouts = readJSON("n5-lesson-blocks.json");
const layoutByLesson = new Map(layouts.map((l) => [l.lesson, l]));
for (const [lessonStr, block] of Object.entries(content.exercises || {})) {
  const lesson = Number(lessonStr);
  const layout = layoutByLesson.get(lesson);
  if (!layout) {
    warnings.push(`exercises: no layout for lesson ${lesson} — skipped`);
    continue;
  }
  // Replace any existing authored block carrying this title marker so re-runs
  // update cleanly instead of duplicating or going stale.
  const marker = block.title && block.title.en;
  if (marker)
    layout.blocks = layout.blocks.filter(
      (b) => !(b.title && b.title.en === marker),
    );
  layout.blocks.push(block);
  addedExercises += (block.items || []).length;
}
writeJSON("n5-lesson-blocks.json", layouts);
// Keep the .authored mirror in sync (it is the editable source of record).
writeJSON("n5-lesson-blocks.authored.json", layouts);

// ── Summary ──────────────────────────────────────────────────────────────────
console.log("\n── Expansion summary ──");
console.log(`  + ${addedExamples} example sentences`);
console.log(`  + ${addedExpl} explanation paragraphs (×2 languages)`);
console.log(`  + ${addedPitfalls} pitfalls (×2 languages)`);
console.log(`  + ${addedExercises} exercise questions`);
if (warnings.length) {
  console.log(`\n⚠ ${warnings.length} warning(s) — review:`);
  for (const w of warnings) console.log("  - " + w);
  process.exitCode = 0; // warnings don't fail the build; they're for review
} else {
  console.log("\n✓ no warnings");
}
